'use client'
import { useState, useEffect, useRef } from 'react'

const ACCENT = '#605dba'
const GREEN = '#10b981'
const RED = '#ef4444'
const AMBER = '#f59e0b'
const BLUE = '#3b82f6'

function useScrollReveal(threshold = 0.15) {
  const ref = useRef(null); const [visible, setVisible] = useState(false)
  useEffect(() => { const el = ref.current; if (!el) return; const obs = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); obs.unobserve(el) } }, { threshold, rootMargin: '0px 0px -60px 0px' }); obs.observe(el); return () => obs.disconnect() }, [threshold])
  return [ref, visible]
}

function DonutChart({ value, max, size = 80, strokeWidth = 8, color }) {
  const [animPct, setAnimPct] = useState(0); const pct = (value / max) * 100
  useEffect(() => { const duration = 1600, startTime = performance.now(); const step = (now) => { const p = Math.min((now - startTime) / duration, 1); setAnimPct(pct * (1 - Math.pow(1 - p, 3))); if (p < 1) requestAnimationFrame(step) }; requestAnimationFrame(step) }, [pct])
  const r = (size - strokeWidth) / 2, circ = 2 * Math.PI * r
  return (<svg width={size} height={size}><circle cx={size/2} cy={size/2} r={r} fill="none" stroke="#f1f5f9" strokeWidth={strokeWidth} /><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color||ACCENT} strokeWidth={strokeWidth} strokeDasharray={`${(animPct/100)*circ} ${circ}`} strokeLinecap="round" transform={`rotate(-90 ${size/2} ${size/2})`} /><text x={size/2} y={size/2} textAnchor="middle" dominantBaseline="middle" fontSize="13" fontWeight="800" fill="#1e293b">{Math.round(animPct)}%</text></svg>)
}

function Section({ title, badge, icon, children }) {
  const [ref, visible] = useScrollReveal(0.1)
  return (<div ref={ref} className={visible ? 'scroll-visible' : 'scroll-hidden'} style={{ marginBottom: '24px' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '30px', height: '30px', borderRadius: '8px', background: ACCENT+'15', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: 800, color: ACCENT }}>{icon}</div><h2 style={{ margin: 0, fontSize: '16px', fontWeight: 600, color: '#1e293b' }}>{title}</h2></div>{badge && <span style={{ background: ACCENT+'12', color: ACCENT, fontSize: '10px', fontWeight: 700, padding: '4px 10px', borderRadius: '12px' }}>{badge}</span>}</div>{visible && children}</div>)
}

// ════════════════════════════════════════════════
// COMPLIANCE REPORTS DATA
// ════════════════════════════════════════════════

const summaryCards = [
  { label: 'Reports Generated (MTD)', value: '48', color: ACCENT },
  { label: 'Auto-Generated by AI', value: '38 (79%)', color: GREEN },
  { label: 'Pending Approval', value: '4', color: AMBER },
  { label: 'Submitted to Authority', value: '12', color: GREEN },
  { label: 'Audit Trail Records', value: '2,840', color: BLUE },
  { label: 'Next Statutory Filing', value: '31 Mar 2026', color: AMBER },
]

// ── Statutory Reports ──
const statutoryReports = [
  { id: 'SR-001', name: 'CEMS Monthly Report — Stack Emissions', authority: 'SPCB Odisha / CPCB', frequency: 'Monthly', lastGenerated: '01 Mar 2026', nextDue: '01 Apr 2026', status: 'Submitted', format: 'CPCB Form V', pages: 28, aiGenerated: true, coverage: 'SO₂, NOx, PM, CO — 6 stacks' },
  { id: 'SR-002', name: 'Environmental Statement (Form V)', authority: 'SPCB Odisha', frequency: 'Annual', lastGenerated: '15 Feb 2026', nextDue: '30 Sep 2026', status: 'Submitted', format: 'SPCB Format', pages: 42, aiGenerated: true, coverage: 'Full plant environmental performance' },
  { id: 'SR-003', name: 'Hazardous Waste Returns (Form 4)', authority: 'SPCB Odisha', frequency: 'Annual', lastGenerated: '28 Feb 2026', nextDue: '30 Jun 2026', status: 'Submitted', format: 'HW Rules 2016', pages: 18, aiGenerated: true, coverage: 'ETP sludge, used oil, spent refractory' },
  { id: 'SR-004', name: 'Consent Compliance Report (CTO)', authority: 'SPCB Odisha', frequency: 'Half-Yearly', lastGenerated: '15 Jan 2026', nextDue: '15 Jul 2026', status: 'Submitted', format: 'SPCB Format', pages: 35, aiGenerated: true, coverage: '42 consent conditions status' },
  { id: 'SR-005', name: 'PAT Scheme — SEC Report (BEE)', authority: 'Bureau of Energy Efficiency', frequency: 'Annual', lastGenerated: '28 Jan 2026', nextDue: '30 Jun 2026', status: 'Submitted', format: 'PAT Form A', pages: 24, aiGenerated: true, coverage: 'Specific energy consumption by process' },
  { id: 'SR-006', name: 'Water Cess Return', authority: 'Water Cess Board', frequency: 'Monthly', lastGenerated: '05 Mar 2026', nextDue: '05 Apr 2026', status: 'Submitted', format: 'WC Form I', pages: 8, aiGenerated: true, coverage: 'Water consumption, effluent discharge' },
  { id: 'SR-007', name: 'EC Compliance Report (6-monthly)', authority: 'MoEFCC / SEIAA', frequency: 'Half-Yearly', lastGenerated: '15 Dec 2025', nextDue: '15 Jun 2026', status: 'Due in 88 days', format: 'MoEFCC Format', pages: 52, aiGenerated: false, coverage: '38 EC conditions + environmental monitoring' },
  { id: 'SR-008', name: 'BRSR Report (SEBI)', authority: 'SEBI / Stock Exchange', frequency: 'Annual', lastGenerated: '15 Feb 2026', nextDue: '15 Feb 2027', status: 'Published', format: 'BRSR Framework', pages: 86, aiGenerated: true, coverage: 'Business Responsibility & Sustainability' },
]

// ── Internal Reports ──
const internalReports = [
  { id: 'IR-001', name: 'Daily Environment Report', frequency: 'Daily', lastGenerated: 'Today 06:00', recipient: 'Plant Head + Environment HOD', pages: 4, aiGenerated: true, content: 'CEMS summary, ambient AQ, effluent, waste, incidents' },
  { id: 'IR-002', name: 'Shift-wise CEMS Summary', frequency: 'Per Shift (3/day)', lastGenerated: 'Today 14:00', recipient: 'Shift Supervisor', pages: 2, aiGenerated: true, content: 'Real-time emission values vs limits, exceedance alerts' },
  { id: 'IR-003', name: 'Weekly Environmental KPI Report', frequency: 'Weekly', lastGenerated: '16 Mar 2026', recipient: 'Management Committee', pages: 8, aiGenerated: true, content: 'CO₂, water, waste, compliance score, NCR status' },
  { id: 'IR-004', name: 'Monthly MIS — Environment', frequency: 'Monthly', lastGenerated: '01 Mar 2026', recipient: 'Board / ESG Committee', pages: 22, aiGenerated: true, content: 'Full environmental MIS with trend analysis' },
  { id: 'IR-005', name: 'Incident / NCR Report', frequency: 'Event-driven', lastGenerated: '12 Mar 2026', recipient: 'Environment Dept + Legal', pages: 6, aiGenerated: false, content: 'NCR-042: ETP sludge recycling rate shortfall' },
  { id: 'IR-006', name: 'Energy Audit Report (Internal)', frequency: 'Quarterly', lastGenerated: '15 Feb 2026', recipient: 'Energy Manager + BEE', pages: 32, aiGenerated: true, content: 'SEC breakdown, gas balance, WHR, PAT performance' },
]

// ── ESG & Voluntary Reports ──
const esgReports = [
  { id: 'ESG-001', name: 'GRI Sustainability Report 2025', framework: 'GRI Standards 2021', status: 'Published', date: '15 Jan 2026', pages: 124, assurance: 'Deloitte (Limited)', coverage: 'GRI 302 (Energy), 303 (Water), 305 (Emissions), 306 (Waste)' },
  { id: 'ESG-002', name: 'CDP Climate Change Questionnaire', framework: 'CDP 2025', status: 'Submitted', date: '31 Jul 2025', pages: 85, assurance: 'Self-declared', coverage: 'Scope 1/2/3, TCFD alignment, SBTi pathway' },
  { id: 'ESG-003', name: 'TCFD Report (Climate Risk)', framework: 'TCFD Recommendations', status: 'Published', date: '15 Feb 2026', pages: 28, assurance: 'KPMG (Reasonable)', coverage: 'Governance, Strategy, Risk Mgmt, Metrics & Targets' },
  { id: 'ESG-004', name: 'Integrated Annual Report — ESG Section', framework: 'IIRC + BRSR', status: 'Draft', date: '—', pages: '~45 (est)', assurance: 'Pending', coverage: 'Integrated with financial report — ESG KPIs' },
  { id: 'ESG-005', name: 'Science-Based Targets (SBTi) Commitment', framework: 'SBTi 1.5°C Pathway', status: 'In Progress', date: '—', pages: '—', assurance: 'SBTi Validation', coverage: 'Near-term: 42% reduction by 2030 (Scope 1+2)' },
]

// ── Audit Trail ──
const auditTrail = [
  { timestamp: '19 Mar 2026, 12:42', user: 'AI Report Engine', action: 'Generated', document: 'Shift-wise CEMS Summary (Shift B)', hash: '0x8f2a..d4e1', verified: true },
  { timestamp: '19 Mar 2026, 06:00', user: 'AI Report Engine', action: 'Generated', document: 'Daily Environment Report', hash: '0x3b7c..a2f8', verified: true },
  { timestamp: '18 Mar 2026, 18:00', user: 'AI Report Engine', action: 'Generated', document: 'Shift-wise CEMS Summary (Shift C)', hash: '0x9e1d..b3c5', verified: true },
  { timestamp: '16 Mar 2026, 09:15', user: 'Dr. Priya Sharma (Env HOD)', action: 'Approved', document: 'Weekly Environmental KPI Report', hash: '0x4a6f..e7d2', verified: true },
  { timestamp: '15 Mar 2026, 14:30', user: 'Rajesh Kumar (Env Mgr)', action: 'Reviewed', document: 'CEMS Monthly Report — Feb 2026', hash: '0x7c3e..f1a9', verified: true },
  { timestamp: '12 Mar 2026, 11:45', user: 'Rajesh Kumar (Env Mgr)', action: 'Created', document: 'NCR-042: ETP Sludge Recycling', hash: '0x2d8b..c4e6', verified: true },
  { timestamp: '05 Mar 2026, 10:00', user: 'AI Report Engine', action: 'Submitted', document: 'Water Cess Return — Feb 2026', hash: '0x6f4a..d8b3', verified: true },
  { timestamp: '01 Mar 2026, 08:30', user: 'AI Report Engine', action: 'Generated + Submitted', document: 'CEMS Monthly Report — Feb 2026 (to SPCB)', hash: '0x1e9c..a7f4', verified: true },
]

// ── Report Templates ──
const reportTemplates = [
  { name: 'CEMS Monthly (CPCB Format)', type: 'Statutory', dataSource: 'CEMS real-time + DCS', autoGenerate: true, approval: 'Environment HOD', sections: 8 },
  { name: 'Environmental Statement (Form V)', type: 'Statutory', dataSource: 'All environmental systems', autoGenerate: true, approval: 'Plant Head', sections: 12 },
  { name: 'PAT Scheme SEC Report', type: 'Statutory', dataSource: 'Energy metering + DCS', autoGenerate: true, approval: 'Energy Manager + BEE', sections: 6 },
  { name: 'Daily Environment Brief', type: 'Internal', dataSource: 'CEMS + Effluent + Waste', autoGenerate: true, approval: 'Auto-distribute', sections: 4 },
  { name: 'Incident / NCR Report', type: 'Internal', dataSource: 'Manual + AI alerts', autoGenerate: false, approval: 'Environment HOD', sections: 5 },
  { name: 'GRI Sustainability Report', type: 'Voluntary', dataSource: 'All plant systems + HR + Finance', autoGenerate: true, approval: 'Board ESG Committee', sections: 18 },
  { name: 'CDP Questionnaire', type: 'Voluntary', dataSource: 'GHG inventory + strategy docs', autoGenerate: false, approval: 'CEO + CSO', sections: 14 },
  { name: 'BRSR Report (SEBI)', type: 'Statutory', dataSource: 'All operations + HR + CSR', autoGenerate: true, approval: 'Board', sections: 22 },
]

// ── AI Recommendations ──
const aiRecommendations = [
  { priority: 'high', title: 'EC Compliance Report due in 88 days — start data collection', reason: 'Half-yearly EC compliance report (SR-007) due 15 Jun 2026. This is the most complex report (52 pages, 38 conditions). AI recommends starting automated data compilation now — 12 conditions require manual site verification and photo documentation.', impact: 'Avoid late submission penalty', model: 'Report Timeline AI', confidence: 95 },
  { priority: 'medium', title: 'Automate Integrated Annual Report ESG section', reason: 'ESG-004 (Annual Report ESG section) is currently manual draft. AI can auto-generate 85% of content from existing data sources (CEMS, energy, waste, HR, CSR). Estimated time saving: 120 man-hours. Template ready for approval.', impact: 'Save 120 man-hours, ensure data consistency', model: 'Auto-Report Generator', confidence: 91 },
  { priority: 'low', title: 'Enhance CDP score — add Scope 3 emissions disclosure', reason: 'Current CDP score B. AI analysis shows Scope 3 emissions (Categories 1, 3, 4, 6) can be estimated from procurement data already available. Adding Scope 3 disclosure addresses 18% of scoring gap for A- rating.', impact: 'CDP B → A- upgrade potential', model: 'ESG Scoring AI', confidence: 87 },
]

// ════════════════════════════════════════════════
// MAIN COMPONENT
// ════════════════════════════════════════════════

export default function ComplianceReports() {
  const [tab, setTab] = useState('all')
  const [animKey, setAnimKey] = useState(0)
  const switchTab = (t) => { setTab(t); setAnimKey(k => k + 1) }
  const show = (c) => tab === 'all' || tab === c

  const tabs = [
    { key: 'all', label: 'All' },
    { key: 'statutory', label: 'Statutory Reports' },
    { key: 'internal', label: 'Internal Reports' },
    { key: 'esg', label: 'ESG / Voluntary' },
    { key: 'audit', label: 'Audit Trail' },
    { key: 'templates', label: 'Report Templates' },
  ]

  return (
    <div key={animKey} style={{ animation: 'fadeUp 0.8s cubic-bezier(0.22,1,0.36,1)' }}>
      <style>{`
        @keyframes fadeUp { from { opacity:0; transform:translateY(24px); } to { opacity:1; transform:translateY(0); } }
        @keyframes slideIn { from { opacity:0; transform:translateX(-16px); } to { opacity:1; transform:translateX(0); } }
        @keyframes pulse { 0%,100% { opacity:1; } 50% { opacity:0.4; } }
        @keyframes scrollReveal { from { opacity:0; transform:translateY(40px); } to { opacity:1; transform:translateY(0); } }
        .scroll-hidden { opacity:0; transform:translateY(40px); }
        .scroll-visible { animation:scrollReveal 0.9s cubic-bezier(0.22,1,0.36,1) forwards; }
      `}</style>

      <div style={st.header}>
        <div>
          <h1 style={st.title}>Compliance Reports</h1>
          <p style={st.sub}>AI-powered audit trails, statutory filings & ESG report generation</p>
        </div>
        <div style={st.headerRight}>
          <span style={st.liveBadge}><span style={{ ...st.liveDot, animation: 'pulse 2s infinite' }} /> Report Engine Active</span>
          <span style={st.aiBadge}>79% Auto-Generated</span>
          <span style={st.timeBadge}>{new Date().toLocaleTimeString()}</span>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '12px', marginBottom: '24px' }}>
        {summaryCards.map((s, i) => (
          <div key={i} style={{ ...st.card, textAlign: 'center', borderTop: `3px solid ${s.color}`, animation: `slideIn 0.7s ease ${i * 0.08}s both` }}>
            <div style={{ fontSize: '10px', color: '#94a3b8', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.3px' }}>{s.label}</div>
            <div style={{ fontSize: '16px', fontWeight: 700, color: s.color }}>{s.value}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: '4px', marginBottom: '24px', flexWrap: 'wrap' }}>
        {tabs.map(t => (<button key={t.key} style={tab === t.key ? st.tabActive : st.tab} onClick={() => switchTab(t.key)}>{t.label}</button>))}
      </div>

      {/* ═══ STATUTORY REPORTS ═══ */}
      {show('statutory') && (
        <Section title="Statutory & Regulatory Reports" badge={`${statutoryReports.length} Reports`} icon="SR">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {statutoryReports.map((r, i) => {
              const statusColor = r.status === 'Submitted' || r.status === 'Published' ? GREEN : r.status.includes('Due') ? AMBER : '#94a3b8'
              return (
                <div key={r.id} style={{ ...st.card, display: 'flex', gap: '16px', alignItems: 'center', animation: `slideIn 0.7s ease ${i * 0.06}s both`, borderLeft: `3px solid ${statusColor}` }}>
                  <div style={{ minWidth: '48px', textAlign: 'center' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: `${ACCENT}12`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke={ACCENT} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /></svg>
                    </div>
                  </div>
                  <div style={{ flex: 2 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '2px' }}>
                      <span style={{ fontSize: '13px', fontWeight: 700, color: '#1e293b' }}>{r.name}</span>
                      {r.aiGenerated && <span style={{ fontSize: '8px', fontWeight: 800, color: '#fff', background: ACCENT, padding: '2px 5px', borderRadius: '3px' }}>AI</span>}
                    </div>
                    <div style={{ fontSize: '10px', color: '#64748b' }}>{r.authority} | {r.format} | {r.pages} pages</div>
                    <div style={{ fontSize: '10px', color: '#94a3b8', marginTop: '2px' }}>{r.coverage}</div>
                  </div>
                  <div style={{ flex: 1, textAlign: 'center' }}>
                    <div style={{ fontSize: '10px', color: '#94a3b8' }}>{r.frequency}</div>
                    <div style={{ fontSize: '11px', fontWeight: 600, color: '#1e293b', marginTop: '2px' }}>Last: {r.lastGenerated}</div>
                    <div style={{ fontSize: '11px', color: AMBER, fontWeight: 500 }}>Next: {r.nextDue}</div>
                  </div>
                  <div style={{ minWidth: '80px', textAlign: 'right' }}>
                    <span style={{ fontSize: '9px', fontWeight: 600, color: statusColor, background: `${statusColor}15`, padding: '3px 10px', borderRadius: '10px' }}>{r.status}</span>
                  </div>
                </div>
              )
            })}
          </div>
        </Section>
      )}

      {/* ═══ INTERNAL REPORTS ═══ */}
      {show('internal') && (
        <Section title="Internal Reports & MIS" badge={`${internalReports.length} Reports`} icon="IR">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '14px' }}>
            {internalReports.map((r, i) => (
              <div key={r.id} style={{ ...st.card, animation: `slideIn 0.7s ease ${i * 0.08}s both`, borderTop: `3px solid ${r.aiGenerated ? GREEN : BLUE}` }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '2px' }}>
                      <span style={{ fontSize: '13px', fontWeight: 700, color: '#1e293b' }}>{r.name}</span>
                      {r.aiGenerated && <span style={{ fontSize: '7px', fontWeight: 800, color: '#fff', background: ACCENT, padding: '2px 4px', borderRadius: '3px' }}>AI</span>}
                    </div>
                    <div style={{ fontSize: '10px', color: '#94a3b8' }}>{r.frequency} | {r.pages} pages</div>
                  </div>
                </div>
                <div style={{ fontSize: '11px', color: '#64748b', lineHeight: '1.5', marginBottom: '8px' }}>{r.content}</div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: '#94a3b8', paddingTop: '8px', borderTop: '1px solid #f1f5f9' }}>
                  <span>Last: {r.lastGenerated}</span>
                  <span>To: {r.recipient}</span>
                </div>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* ═══ ESG / VOLUNTARY ═══ */}
      {show('esg') && (
        <Section title="ESG & Voluntary Disclosure Reports" badge={`${esgReports.length} Reports`} icon="ES">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {esgReports.map((r, i) => {
              const statusColor = r.status === 'Published' || r.status === 'Submitted' ? GREEN : r.status === 'Draft' ? AMBER : BLUE
              return (
                <div key={r.id} style={{ ...st.card, borderLeft: `4px solid ${statusColor}`, animation: `slideIn 0.7s ease ${i * 0.1}s both` }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                    <div>
                      <div style={{ fontSize: '15px', fontWeight: 700, color: '#1e293b', marginBottom: '2px' }}>{r.name}</div>
                      <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                        <span style={{ fontSize: '10px', color: ACCENT, fontWeight: 600 }}>{r.framework}</span>
                        <span style={{ fontSize: '9px', fontWeight: 600, color: statusColor, background: `${statusColor}15`, padding: '2px 8px', borderRadius: '10px' }}>{r.status}</span>
                      </div>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                      <div style={{ fontSize: '12px', fontWeight: 600, color: '#1e293b' }}>{r.date}</div>
                      <div style={{ fontSize: '10px', color: '#94a3b8' }}>{r.pages} pages</div>
                    </div>
                  </div>
                  <div style={{ fontSize: '11px', color: '#64748b', lineHeight: '1.5', marginBottom: '6px' }}>{r.coverage}</div>
                  <div style={{ fontSize: '10px', color: '#94a3b8' }}>Assurance: {r.assurance}</div>
                </div>
              )
            })}
          </div>
        </Section>
      )}

      {/* ═══ AUDIT TRAIL ═══ */}
      {show('audit') && (
        <Section title="Blockchain-Anchored Audit Trail" badge="Tamper-Proof" icon="AT">
          <div style={st.card}>
            <div style={{ display: 'grid', gridTemplateColumns: '160px 160px 80px 1fr 100px 40px', gap: '8px', padding: '10px 12px', background: '#f8fafc', borderRadius: '8px', marginBottom: '4px' }}>
              {['Timestamp', 'User / Engine', 'Action', 'Document', 'Hash', '✓'].map(h => (<div key={h} style={{ fontSize: '9px', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.3px' }}>{h}</div>))}
            </div>
            {auditTrail.map((a, i) => {
              const actionColor = a.action === 'Generated' ? GREEN : a.action === 'Approved' ? ACCENT : a.action === 'Submitted' || a.action === 'Generated + Submitted' ? BLUE : AMBER
              return (
                <div key={i} style={{ display: 'grid', gridTemplateColumns: '160px 160px 80px 1fr 100px 40px', gap: '8px', padding: '12px', borderRadius: '8px', border: '1px solid #f1f5f9', marginBottom: '3px', animation: `slideIn 0.6s ease ${i * 0.05}s both` }}>
                  <div style={{ fontSize: '11px', color: '#64748b', fontFamily: 'monospace' }}>{a.timestamp}</div>
                  <div style={{ fontSize: '11px', fontWeight: 500, color: a.user.includes('AI') ? ACCENT : '#1e293b' }}>{a.user}</div>
                  <div><span style={{ fontSize: '9px', fontWeight: 600, color: actionColor, background: `${actionColor}15`, padding: '2px 6px', borderRadius: '4px' }}>{a.action}</span></div>
                  <div style={{ fontSize: '11px', color: '#1e293b', fontWeight: 500 }}>{a.document}</div>
                  <div style={{ fontSize: '9px', color: '#94a3b8', fontFamily: 'monospace' }}>{a.hash}</div>
                  <div style={{ textAlign: 'center' }}>
                    {a.verified && <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={GREEN} strokeWidth="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" /><polyline points="22 4 12 14.01 9 11.01" /></svg>}
                  </div>
                </div>
              )
            })}
          </div>
          <div style={{ ...st.card, display: 'flex', gap: '32px', marginTop: '14px' }}>
            <div><span style={st.tinyLabel}>Total Records </span><span style={st.tinyVal}>2,840</span></div>
            <div><span style={st.tinyLabel}>AI-Generated </span><span style={{ ...st.tinyVal, color: GREEN }}>2,248 (79%)</span></div>
            <div><span style={st.tinyLabel}>Human Actions </span><span style={st.tinyVal}>592</span></div>
            <div><span style={st.tinyLabel}>Integrity </span><span style={{ ...st.tinyVal, color: GREEN }}>100% Verified</span></div>
          </div>
        </Section>
      )}

      {/* ═══ REPORT TEMPLATES ═══ */}
      {show('templates') && (
        <Section title="Report Templates & Configuration" badge={`${reportTemplates.length} Templates`} icon="TP">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '14px' }}>
            {reportTemplates.map((t, i) => {
              const typeColor = t.type === 'Statutory' ? RED : t.type === 'Internal' ? BLUE : GREEN
              return (
                <div key={t.name} style={{ ...st.card, animation: `slideIn 0.7s ease ${i * 0.06}s both`, borderTop: `3px solid ${typeColor}` }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                    <span style={{ fontSize: '9px', fontWeight: 600, color: typeColor, background: `${typeColor}15`, padding: '2px 8px', borderRadius: '10px' }}>{t.type}</span>
                    {t.autoGenerate && <span style={{ fontSize: '7px', fontWeight: 800, color: '#fff', background: ACCENT, padding: '2px 4px', borderRadius: '3px' }}>AI AUTO</span>}
                  </div>
                  <div style={{ fontSize: '12px', fontWeight: 600, color: '#1e293b', lineHeight: '1.3', marginBottom: '8px' }}>{t.name}</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', fontSize: '10px', color: '#64748b' }}>
                    <div>Data: {t.dataSource}</div>
                    <div>Approval: {t.approval}</div>
                    <div>Sections: {t.sections}</div>
                  </div>
                </div>
              )
            })}
          </div>
        </Section>
      )}

      {/* ═══ AI RECOMMENDATIONS ═══ */}
      <Section title="AI Report Recommendations" badge={`${aiRecommendations.length} Active`} icon="AI">
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          {aiRecommendations.map((rec, i) => {
            const priColors = { high: RED, medium: AMBER, low: GREEN }
            return (
              <div key={i} style={{ ...st.card, borderLeft: `4px solid ${priColors[rec.priority]}`, animation: `slideIn 0.7s ease ${i * 0.1}s both` }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ fontSize: '9px', fontWeight: 700, textTransform: 'uppercase', color: '#fff', background: priColors[rec.priority], padding: '2px 6px', borderRadius: '3px' }}>{rec.priority}</span>
                    <span style={{ fontSize: '13px', fontWeight: 600, color: '#1e293b' }}>{rec.title}</span>
                  </div>
                  <span style={{ fontSize: '10px', color: '#94a3b8', background: '#f1f5f9', padding: '2px 8px', borderRadius: '4px' }}>{rec.model}</span>
                </div>
                <p style={{ margin: '0 0 8px', fontSize: '12px', color: '#4a5568', lineHeight: '1.6' }}>{rec.reason}</p>
                <span style={{ fontSize: '10px', color: '#94a3b8' }}>Confidence: <strong style={{ color: ACCENT }}>{rec.confidence}%</strong> | Impact: <strong style={{ color: GREEN }}>{rec.impact}</strong></span>
              </div>
            )
          })}
        </div>
      </Section>

      <div style={st.aiFooter}>
        <div style={st.aiFooterIcon}>AI</div>
        <div>
          <div style={{ fontSize: '13px', fontWeight: 600, color: '#1e293b', marginBottom: '4px' }}>AI Report Engine — Compliance Reports</div>
          <div style={{ fontSize: '12px', color: '#64748b', lineHeight: 1.6 }}>
            Auto-generating 79% of compliance reports from real-time plant data. 8 statutory reports, 6 internal reports, 5 ESG disclosures tracked.
            Audit trail: 2,840 blockchain-anchored records with 100% integrity verification. AI-powered report engine uses iFactory-Report-LLM-7B
            for narrative generation, data validation, and formatting. Average report generation time: 4.5 seconds for daily reports, 12 minutes for annual reports.
            Zero late statutory filings in 24 months. Next critical deadline: EC Compliance Report (15 Jun 2026).
          </div>
        </div>
      </div>
    </div>
  )
}

const st = {
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px' },
  title: { margin: 0, fontSize: '22px', fontWeight: 700, color: '#1e293b' },
  sub: { margin: '2px 0 0', fontSize: '13px', color: '#94a3b8' },
  headerRight: { display: 'flex', gap: '8px', alignItems: 'center', flexWrap: 'wrap' },
  liveBadge: { display: 'flex', alignItems: 'center', gap: '6px', background: '#f0fdf4', color: GREEN, border: '1px solid #bbf7d0', borderRadius: '16px', padding: '5px 12px', fontSize: '11px', fontWeight: 600 },
  liveDot: { width: '6px', height: '6px', borderRadius: '50%', background: GREEN },
  aiBadge: { background: ACCENT + '15', color: ACCENT, fontSize: '11px', fontWeight: 700, padding: '5px 12px', borderRadius: '16px' },
  timeBadge: { fontSize: '11px', color: '#94a3b8', background: '#f8fafc', padding: '5px 12px', borderRadius: '16px', border: '1px solid #e8ecf1' },
  card: { background: '#fff', border: '1px solid #e8ecf1', borderRadius: '12px', padding: '18px' },
  tab: { background: '#fff', border: '1px solid #e8ecf1', borderRadius: '8px', padding: '7px 14px', fontSize: '12px', color: '#64748b', cursor: 'pointer', fontWeight: 500 },
  tabActive: { background: ACCENT, border: `1px solid ${ACCENT}`, borderRadius: '8px', padding: '7px 14px', fontSize: '12px', color: '#fff', cursor: 'pointer', fontWeight: 600 },
  tinyLabel: { fontSize: '10px', color: '#94a3b8' },
  tinyVal: { fontSize: '13px', fontWeight: 700, color: '#1e293b' },
  aiFooter: { display: 'flex', gap: '14px', background: '#fff', border: `1px solid ${ACCENT}30`, borderRadius: '12px', padding: '18px', marginTop: '10px' },
  aiFooterIcon: { width: '36px', height: '36px', borderRadius: '8px', background: ACCENT, color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: 800, flexShrink: 0 },
}
